name: Build OIDBS Release

on:
  # schedule:
  #  - cron:  "*/5 * * * *"
  push:
    tags:
      - "v*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - uses: actions/checkout@v2
    - name: Build OIDBS Release
      run: cargo build --release --verbose
    - name: Strip binary
      run: strip ./target/release/oidbs
    - name: Get current postfix 1
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "POSTFIX=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Get current postfix 2
      if: startsWith(github.ref, 'refs/tags/v') != true
      run: echo "POSTFIX=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV  
    - name: Pack OIDBS files
      run: |
        zip -j oidbs_x64_${{ env.POSTFIX }}.zip ./target/release/oidbs LICENSE
        zip -r oidbs_x64_${{ env.POSTFIX }}.zip models
    - name: Create OIDBS Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: oidbs_x64_${{ env.POSTFIX }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: false
